config/routes.rb
Airbase::Application.routes.draw do

  devise_for :users

  resources :aircraft do
    resources :aircraft_histories
    collection do
      post :sort
    end
  end

  resources :airports do
    resources :airport_visits do
      resources :seenlists
    end
  end

  resources :aircraft_statuses

  get "home/index"

  root :to => "home#index"

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
  belongs_to :aircraft_status
  has_many   :aircraft_histories

  # cattr_reader :per_page
  # @@per_page = 50

  def self.search(search, page)
      paginate :per_page => 20,
               :page     => page,
               :conditions => ['aircraft_type like ?', "%#{search}%"],
               :order => 'aircraft_type, constructors_number'
  end
end

app/controllers/aircraft_controller.rb
class AircraftController < ApplicationController
  # GET /aircraft
  # GET /aircraft.xml
  def index
    # @aircraft = Aircraft.all
    # @aircraft = Aircraft.paginate :page => params[:page] 
    @aircraft = Aircraft.search(params[:search], params[:page])

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.xml  { render :xml => @aircraft }
    # end
  end

  # GET /aircraft/1
  # GET /aircraft/1.xml
  def show
    @aircraft = Aircraft.find(params[:id])

    # respond_to do |format|
      # format.html # show.html.erb
      # format.xml  { render :xml => @aircraft }
    # end
  end

  # GET /aircraft/new
  # GET /aircraft/new.xml
  def new
    @aircraft = Aircraft.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @aircraft }
    end
  end

  # GET /aircraft/1/edit
  def edit
    @aircraft = Aircraft.find(params[:id])
  end

  # POST /aircraft
  # POST /aircraft.xml
  def create
    @aircraft = Aircraft.new(params[:aircraft])

    respond_to do |format|
      if @aircraft.save
        format.html { redirect_to(@aircraft, :notice => 'Aircraft was successfully created.') }
        format.xml  { render :xml => @aircraft, :status => :created, :location => @aircraft }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @aircraft.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aircraft/1
  # PUT /aircraft/1.xml
  def update
    @aircraft = Aircraft.find(params[:id])

    respond_to do |format|
      if @aircraft.update_attributes(params[:aircraft])
        format.html { redirect_to(@aircraft, :notice => 'Aircraft was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @aircraft.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aircraft/1
  # DELETE /aircraft/1.xml
  def destroy
    @aircraft = Aircraft.find(params[:id])
    @aircraft.destroy

    respond_to do |format|
      format.html { redirect_to(aircraft_index_url) }
      format.xml  { head :ok }
    end
  end

  def sort
    @aircraft = Aircraft.find(params[:id])
    @aircraft.aircraft_histories.each do |ah|
       ah.aircraft_sequence = params['ah-list' ].index(ah.id.to_s) + 1
       ah.save
    end
    render :nothing => true
  end
end

app/helpers/aircraft_helper.rb
module AircraftHelper
end

app/views/aircraft/_form.html.erb
<%= form_for(@aircraft) do |f| %>
  <% if @aircraft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aircraft.errors.count, "error") %> prohibited this aircraft from being saved:</h2>

      <ul>
      <% @aircraft.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :aircraft_type %><br />
    <%= f.text_field :aircraft_type %>
  </div>
  <div class="field">
    <%= f.label :constructors_number %><br />
    <%= f.text_field :constructors_number %>
  </div>
  <div class="field">
    <%= f.label :line_number %><br />
    <%= f.text_field :line_number %>
  </div>
  <div class="field">
    <%=
      # @statuses = AircraftStatus.find(:all, :order => "description")
      f.label :aircraft_status 
     %>
    <br />
    <%= f.collection_select(:aircraft_status_id, AircraftStatus.all, :id, :description) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aircraft/edit.html.erb
<h1>Editing aircraft</h1>

<%= render 'form' %>

<%= link_to 'Show', @aircraft %> |
<%= link_to 'Back', aircraft_index_path %>

app/views/aircraft/index.html.erb
<h1>Aircraft</h1>

<%= form_tag request.path, :method => 'get' do %>
  <%= content_tag :label do %>
    Search term:
    <%= text_field_tag :search, params[:search] %>
  <% end %>
<% end %>

<table>
  <tr>
    <th>Type</th>
    <th>C/N</th>
    <th>L/N</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aircraft.each do |aircraft| %>
  <tr>
    <td><%= aircraft.aircraft_type %></td>
    <td><%= aircraft.constructors_number %></td>
    <td><%= aircraft.line_number %></td>
    <td><%= aircraft.aircraft_status.description %></td>
    <td><%= link_to 'Show', aircraft %></td>
    <td><%= link_to 'Edit', edit_aircraft_path(aircraft) %></td>
    <td><%= link_to 'Destroy', aircraft, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>


<%= will_paginate @aircraft %>

<%= link_to 'New Aircraft', new_aircraft_path %>

app/views/aircraft/new.html.erb
<h1>New aircraft</h1>

<%= render 'form' %>

<%= link_to 'Back', aircraft_index_path %>

app/views/aircraft/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Aircraft</h2>

<table>
  <tr>
    <th>Aircraft Type</th>
    <th>C/N</th>
    <th>L/N</th>
    <th>Status</th>
  </tr>
  <tr>
    <td><%= @aircraft.aircraft_type %></td>
    <td><%= @aircraft.constructors_number %></td>
    <td><%= @aircraft.line_number %></td>
    <td><%= @aircraft.aircraft_status.description %></td>
  </tr>
</table>

<h2>Registration History</h2>

<table>
  <tr>
    <th>Sequence</th>
    <th>Registration</th>
    <th>Aircraft Details</th>
    <th/>
  </tr>
</table>

<div id="aircraft-list">
<ul id="ah-list" >

<%= render :partial    => "aircraft_histories/aircraft_history",
           :collection => @aircraft.aircraft_histories %>

</ul>
</div>

<%= sortable_element 'ah-list',
    :url => { :action => "sort" , :id => @aircraft },
    :complete => visual_effect(:highlight, 'ah-list')

 %>

<h2>Add a New Registration</h2>

<%= render "aircraft_histories/form" %>



<%= link_to 'Edit', edit_aircraft_path(@aircraft) %> |
<%= link_to 'Back', aircraft_index_path %>