config/routes.rb
Airbase::Application.routes.draw do

  devise_for :users

  resources :aircraft do
    resources :aircraft_histories
    collection do
      post :sort
    end
  end

  resources :airports do
    resources :airport_visits do
      resources :seenlists
    end
  end

  resources :aircraft_statuses

  get "home/index"

  root :to => "home#index"

end

app/controllers/aircraft_statuses_controller.rb
class AircraftStatusesController < ApplicationController
  # GET /aircraft_statuses
  # GET /aircraft_statuses.xml
  def index
    @aircraft_statuses = AircraftStatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @aircraft_statuses }
    end
  end

  # GET /aircraft_statuses/1
  # GET /aircraft_statuses/1.xml
  def show
    @aircraft_status = AircraftStatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @aircraft_status }
    end
  end

  # GET /aircraft_statuses/new
  # GET /aircraft_statuses/new.xml
  def new
    @aircraft_status = AircraftStatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @aircraft_status }
    end
  end

  # GET /aircraft_statuses/1/edit
  def edit
    @aircraft_status = AircraftStatus.find(params[:id])
  end

  # POST /aircraft_statuses
  # POST /aircraft_statuses.xml
  def create
    @aircraft_status = AircraftStatus.new(params[:aircraft_status])

    respond_to do |format|
      if @aircraft_status.save
        format.html { redirect_to(@aircraft_status, :notice => 'Aircraft status was successfully created.') }
        format.xml  { render :xml => @aircraft_status, :status => :created, :location => @aircraft_status }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @aircraft_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /aircraft_statuses/1
  # PUT /aircraft_statuses/1.xml
  def update
    @aircraft_status = AircraftStatus.find(params[:id])

    respond_to do |format|
      if @aircraft_status.update_attributes(params[:aircraft_status])
        format.html { redirect_to(@aircraft_status, :notice => 'Aircraft status was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @aircraft_status.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /aircraft_statuses/1
  # DELETE /aircraft_statuses/1.xml
  def destroy
    @aircraft_status = AircraftStatus.find(params[:id])
    @aircraft_status.destroy

    respond_to do |format|
      format.html { redirect_to(aircraft_statuses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/aircraft_statuses_helper.rb
module AircraftStatusesHelper
end

app/views/aircraft_statuses/_form.html.erb
<%= form_for(@aircraft_status) do |f| %>
  <% if @aircraft_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aircraft_status.errors.count, "error") %> prohibited this aircraft_status from being saved:</h2>

      <ul>
      <% @aircraft_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/aircraft_statuses/edit.html.erb
<h1>Editing aircraft_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @aircraft_status %> |
<%= link_to 'Back', aircraft_statuses_path %>

app/views/aircraft_statuses/index.html.erb
<h1>Aircraft Statuses</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @aircraft_statuses.each do |aircraft_status| %>
  <tr>
    <td><%= aircraft_status.description %></td>
    <td><%= link_to 'Show', aircraft_status %></td>
    <td><%= link_to 'Edit', edit_aircraft_status_path(aircraft_status) %></td>
    <td><%= link_to 'Destroy', aircraft_status, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Aircraft status', new_aircraft_status_path %>

app/views/aircraft_statuses/new.html.erb
<h1>New aircraft_status</h1>

<%= render 'form' %>

<%= link_to 'Back', aircraft_statuses_path %>

app/views/aircraft_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @aircraft_status.description %>
</p>


<%= link_to 'Edit', edit_aircraft_status_path(@aircraft_status) %> |
<%= link_to 'Back', aircraft_statuses_path %>