config/routes.rb
Airbase::Application.routes.draw do

  devise_for :users

  resources :aircraft do
    resources :aircraft_histories
    collection do
      post :sort
    end
  end

  resources :airports do
    resources :airport_visits do
      resources :seenlists
    end
  end

  resources :aircraft_statuses

  get "home/index"

  root :to => "home#index"

end

app/models/airport.rb
class Airport < ActiveRecord::Base
	has_many :airport_visits, :dependent => :destroy
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  # GET /airports
  # GET /airports.xml
  def index
    @airports = Airport.paginate :page => params[:page], :per_page => 20
    # @airports = Airport.all

    # respond_to do |format|
      # format.html # index.html.erb
      # format.xml  { render :xml => @airports }
    # end
  end

  # GET /airports/1
  # GET /airports/1.xml
  def show
    @airport = Airport.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @airport }
    end
  end

  # GET /airports/new
  # GET /airports/new.xml
  def new
    @airport = Airport.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @airport }
    end
  end

  # GET /airports/1/edit
  def edit
    @airport = Airport.find(params[:id])
  end

  # POST /airports
  # POST /airports.xml
  def create
    @airport = Airport.new(params[:airport])

    respond_to do |format|
      if @airport.save
        format.html { redirect_to(@airport, :notice => 'Airport was successfully created.') }
        format.xml  { render :xml => @airport, :status => :created, :location => @airport }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @airport.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /airports/1
  # PUT /airports/1.xml
  def update
    @airport = Airport.find(params[:id])

    respond_to do |format|
      if @airport.update_attributes(params[:airport])
        format.html { redirect_to(airports_url, :notice => 'Airport was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @airport.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.xml
  def destroy
    @airport = Airport.find(params[:id])
    @airport.destroy

    respond_to do |format|
      format.html { redirect_to(airports_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_form.html.erb
<%= form_for(@airport) do |f| %>
  <% if @airport.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airport.errors.count, "error") %> prohibited this airport from being saved:</h2>

      <ul>
      <% @airport.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :iata_code %><br />
    <%= f.text_field :iata_code %>
  </div>
  <div class="field">
    <%= f.label :icao_code %><br />
    <%= f.text_field :icao_code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/airports/edit.html.erb
<h1>Editing airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airports_path %>

app/views/airports/index.html.erb
<h1>Airports</h1>

<table>
  <tr>
    <th>Name</th>
    <th>IATA Code</th>
    <th>ICAO Code</th>
    <th>Visits</th>
    <th>Earliest</th>
    <th>Latest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @airports.each do |airport| %>
  <tr>
    <td><%= airport.name %></td>
    <td><%= airport.iata_code %></td>
    <td><%= airport.icao_code %></td>
    <td><%= airport.airport_visits.count %></td>
    <td><%= airport.airport_visits.minimum(:visit_date) %></td>
    <td><%= airport.airport_visits.maximum(:visit_date) %></td>
    <td><%= link_to 'Show', airport %></td>
    <td><%= link_to 'Edit', edit_airport_path(airport) %></td>
    <td><%= link_to 'Destroy', airport, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
 
<%= will_paginate @airports %>

<%= link_to 'Add New Airport', new_airport_path %>

app/views/airports/new.html.erb
<h1>New airport</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path %>

app/views/airports/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @airport.name %></h2>

  <p>IATA Code: <%= @airport.iata_code %></p>
  <p>ICAO Code: <%= @airport.icao_code %></p>

<h2>Visit Dates</h2>

<%= render :partial    => "airport_visits/airport_visit",
           :collection => @airport.airport_visits %>

<h2>Add a New Visit</h2>

<%= render "airport_visits/form" %>

<%= link_to 'Edit', edit_airport_path(@airport) %> |
<%= link_to 'Back', airports_path %>