config/routes.rb
Airbase::Application.routes.draw do

  devise_for :users

  resources :aircraft do
    resources :aircraft_histories
    collection do
      post :sort
    end
  end

  resources :airports do
    resources :airport_visits do
      resources :seenlists
    end
  end

  resources :aircraft_statuses

  get "home/index"

  root :to => "home#index"

end

app/models/airport_visit.rb
class AirportVisit < ActiveRecord::Base
  belongs_to :airport
  has_many   :seenlists
end

app/controllers/airport_visits_controller.rb
class AirportVisitsController < ApplicationController
  # GET /airport_visits
  # GET /airport_visits.xml
  def index
    @airport_visits = AirportVisit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @airport_visits }
    end
  end

  # GET /airport_visits/1
  # GET /airport_visits/1.xml
  def show
    @airport_visit = AirportVisit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @airport_visit }
    end
  end

  # GET /airport_visits/new
  # GET /airport_visits/new.xml
  def new
    @airport_visit = AirportVisit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @airport_visit }
    end
  end

  # GET /airport_visits/1/edit
  def edit
    @airport_visit = AirportVisit.find(params[:id])
  end

  # POST /airport_visits
  # POST /airport_visits.xml
  def create
    @airport = Airport.find(params[:airport_id])
    @airport_visit = @airport.airport_visits.create(params[:airport_visit])
    redirect_to airport_path(@airport)
  end

  # PUT /airport_visits/1
  # PUT /airport_visits/1.xml
  def update
    @airport_visit = AirportVisit.find(params[:id])

    respond_to do |format|
      if @airport_visit.update_attributes(params[:airport_visit])
        format.html { redirect_to(@airport_visit, :notice => 'Airport visit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @airport_visit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /airport_visits/1
  # DELETE /airport_visits/1.xml
  def destroy
    @airport = Airport.find(params[:airport_id])
    @airport_visit = @airport.airport_visits.find(params[:id])
    @airport_visit.destroy
    redirect_to airport_path(@airport)
  end
end

app/helpers/airport_visits_helper.rb
module AirportVisitsHelper
end

app/views/airport_visits/_airport_visit.html.erb
   <p>
      <%= airport_visit.visit_date %> 
      <%= airport_visit.seenlists.count %>
       
      <%= # if airport_visit.seenlists.count = 0 then
          link_to 'Add Sightings', new_airport_airport_visit_seenlist_path (
           airport_visit.airport,
           airport_visit
          ) 
          # else 
   #       link_to 'Add Sightings', airport_airport_visit_seenlist_path (
   #          airport_visit.airport,
   #          airport_visit,
   #          airport_visit.seenlist
   #       )
                                   
          # end
       %>
      <%= link_to 'Delete Visit' , [airport_visit.airport, airport_visit], 
                  :confirm => "Are you sure ?",
                  :method  => :delete 
      %>
   </p>

app/views/airport_visits/_form.html.erb
<%= form_for([@airport, @airport.airport_visits.build]) do |f| %>
        <%= f.error_messages %>
        <div class="field">
                <%= f.label :visit_date %><br />
                <%= f.date_select :visit_date %>
        </div>
        <div class="actions">
                <%= f.submit %>
        </div>
<% end %>

app/views/airport_visits/edit.html.erb
<h1>Editing airport_visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport_visit %> |
<%= link_to 'Back', airport_visits_path %>

app/views/airport_visits/index.html.erb
<h1>Listing airport_visits</h1>

<table>
  <tr>
    <th>Airport</th>
    <th>Visit date</th>
    <th>Aircraft seen</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @airport_visits.each do |airport_visit| %>
  <tr>
    <td><%= airport_visit.airport_id %></td>
    <td><%= airport_visit.visit_date %></td>
    <td><%= airport_visit.seenlist.count %></td>
    <td><%= link_to 'Show', airport_visit %></td>
    <td><%= link_to 'Edit', edit_airport_visit_path(airport_visit) %></td>
    <td><%= link_to 'Destroy', airport_visit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Airport visit', new_airport_visit_path %>

app/views/airport_visits/new.html.erb
<h1>New airport_visit</h1>

<%= render 'form' %>

<%= link_to 'Back', airport_visits_path %>

app/views/airport_visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Airport:</b>
  <%= @airport_visit.airport_id %>
</p>

<p>
  <b>Visit date:</b>
  <%= @airport_visit.visit_date %>
</p>


<%= link_to 'Edit', edit_airport_visit_path(@airport_visit) %> |
<%= link_to 'Back', airport_visits_path %>